### ISSUE TITLE
[Question] Which styles do you need to modify to create a custom theme like this?

### ISSUE THREAD

**Issue by ekillops** [dracula/fman#1]
Your theme looks great. I took a stab a creating my own though trial and error from the base theme but didn't get as polished as yours. I was wondering if you could point to the key css/qss properties you modified to create this theme? I would love to create a version for Nord which is my preferred IDE theme. Thanks!

**Comment by sf-pear** [comment]
Hey, sorry I don't remember exactly what I changed, it was a while ago. I think the last piece to make it look good were the scrollbars. Just found this: https://www.w3docs.com/tools/code-diff/ you could use it to compare my code with the original one to see the changes :) hope that helps!

**Comment by ekillops** [comment]
Thanks for the response! Diffing was interesting, looked like you had to add some new styles in addition to modifying the existing ones. I ended up doing a find-and-replace on the main colors of your theme to create mine. It worked pretty well

**Comment by sf-pear** [comment]
Glad it helped!
